/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as MediaSplatRouteImport } from './routes/media/$'
import { Route as ApiDashboardLoginRouteImport } from './routes/api/dashboard/login'
import { Route as ApiWebsocketStatsRouteImport } from './routes/api/websocket/stats'
import { Route as ApiWhatsappSplatRouteImport } from './routes/api/whatsapp/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardLoginRoute = ApiDashboardLoginRouteImport.update({
  id: '/api/dashboard/login',
  path: '/api/dashboard/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebsocketStatsRoute = ApiWebsocketStatsRouteImport.update({
  id: '/api/websocket/stats',
  path: '/api/websocket/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappSplatRoute = ApiWhatsappSplatRouteImport.update({
  id: '/api/whatsapp/$',
  path: '/api/whatsapp/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/media/$': typeof MediaSplatRoute
  '/api/dashboard/login': typeof ApiDashboardLoginRoute
  '/api/websocket/stats': typeof ApiWebsocketStatsRoute
  '/api/whatsapp/$': typeof ApiWhatsappSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/media/$': typeof MediaSplatRoute
  '/api/dashboard/login': typeof ApiDashboardLoginRoute
  '/api/websocket/stats': typeof ApiWebsocketStatsRoute
  '/api/whatsapp/$': typeof ApiWhatsappSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/media/$': typeof MediaSplatRoute
  '/api/dashboard/login': typeof ApiDashboardLoginRoute
  '/api/websocket/stats': typeof ApiWebsocketStatsRoute
  '/api/whatsapp/$': typeof ApiWhatsappSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/health'
    | '/media/$'
    | '/api/dashboard/login'
    | '/api/websocket/stats'
    | '/api/whatsapp/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/health'
    | '/media/$'
    | '/api/dashboard/login'
    | '/api/websocket/stats'
    | '/api/whatsapp/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/health'
    | '/media/$'
    | '/api/dashboard/login'
    | '/api/websocket/stats'
    | '/api/whatsapp/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ApiHealthRoute: typeof ApiHealthRoute
  MediaSplatRoute: typeof MediaSplatRoute
  ApiDashboardLoginRoute: typeof ApiDashboardLoginRoute
  ApiWebsocketStatsRoute: typeof ApiWebsocketStatsRoute
  ApiWhatsappSplatRoute: typeof ApiWhatsappSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/login': {
      id: '/api/dashboard/login'
      path: '/api/dashboard/login'
      fullPath: '/api/dashboard/login'
      preLoaderRoute: typeof ApiDashboardLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/websocket/stats': {
      id: '/api/websocket/stats'
      path: '/api/websocket/stats'
      fullPath: '/api/websocket/stats'
      preLoaderRoute: typeof ApiWebsocketStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/$': {
      id: '/api/whatsapp/$'
      path: '/api/whatsapp/$'
      fullPath: '/api/whatsapp/$'
      preLoaderRoute: typeof ApiWhatsappSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ApiHealthRoute: ApiHealthRoute,
  MediaSplatRoute: MediaSplatRoute,
  ApiDashboardLoginRoute: ApiDashboardLoginRoute,
  ApiWebsocketStatsRoute: ApiWebsocketStatsRoute,
  ApiWhatsappSplatRoute: ApiWhatsappSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
